[package]
name = "anvil"
version = "0.0.1"
authors = ["Victor Berger <victor.berger@m4x.org>", "Drakulix (Victoria Brekenfeld)"]
license = "MIT"
publish = false
edition = "2018"

[dependencies]
bitflags = "1.2.1"
thiserror = "1"
xcursor = { version = "0.3.3", optional = true }
image = { version = "0.24.0", default-features = false, optional = true }
fps_ticker = { version = "1.0.0", optional = true }
rand = "0.8"
slog = { version = "2.1.1" }
slog-term = "2.8"
slog-async = "2.2"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"
xkbcommon = "0.4.0"

[lib]
crate-type = ["lib", "cdylib"]

# This dependency will only be included when targeting Android
[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.6.2" # Substitute this with the latest ndk-glue version you wish to use

[dependencies.smithay]
path = ".."
default-features = false
features = [ "desktop", "wayland_frontend", "slog-stdlog" ]

[dependencies.x11rb]
optional = true
version = "0.10.0"
default-features = false
features = [ "composite" ]

[build-dependencies]
gl_generator = "0.14"

[features]

default = [ "egl", "winit", "xwayland" ]
egl = [ "smithay/use_system_lib", "smithay/backend_egl" ]
winit = [ "smithay/backend_winit" ]
udev = [ "smithay/backend_libinput", "smithay/backend_udev", "smithay/backend_drm", "smithay/backend_gbm", "smithay/backend_egl", "smithay/backend_session", "image", "smithay/renderer_gl", "smithay/renderer_multi", "xcursor" ]
logind = [ "smithay/backend_session_logind" ]
elogind = ["logind", "smithay/backend_session_elogind" ]
libseat = ["smithay/backend_session_libseat" ]
xwayland = [ "smithay/xwayland", "x11rb", "smithay/x11rb_event_source" ]
x11 = [ "smithay/backend_x11", "x11rb", "egl", "smithay/renderer_gl" ]
debug = [ "fps_ticker", "image/png" ]
test_all_features = ["default", "debug"]

[package.metadata.android]
# Specifies the package property of the manifest.
package = "com.github.lovelyyfiaaa.Waylovely"

# Specifies the array of targets to build for.
build_targets = [ "aarch64-linux-android" ] # For now we'll just build for Aarch64 <3

# Name for final APK file.
# Defaults to package name.
apk_name = "waylovely"
runtime_libs = "../../app/libs"

# See https://developer.android.com/guide/topics/manifest/uses-sdk-element

[package.metadata.android.sdk]
min_sdk_version = 29
target_sdk_version = 32